# 1.

In [6]:
import numpy as np

# 2.

In [4]:

# Print NumPy version
print("NumPy Version:", np.__version__)

# Print NumPy configuration
print("\nNumPy Configuration:")
print(np.show_config())


NumPy Version: 1.26.2

NumPy Configuration:
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30152",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.5",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30152",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas64",
      "found": true,
      "version": "0.3.23.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITIN

c:\Python312\Lib\site-packages\numpy\__config__.py:149: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


# 3.

In [5]:
# Create a null vector of size 10
null_vector = np.zeros(10)

print("Null Vector:")
print(null_vector)


Null Vector:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 4.

In [6]:
# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Find the memory size of the array
memory_size = my_array.nbytes

print(f"Memory size of the array: {memory_size} bytes")


Memory size of the array: 20 bytes


# 5.

In [7]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

# 6.

In [8]:

# Create a null vector of size 10
null_vector = np.zeros(10)

# Set the fifth value (index 4) to 1
null_vector[4] = 1

print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 7.

In [9]:
# Create a vector with values ranging from 10 to 49
vector = np.arange(10, 50)

print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 8.

In [10]:
# Create a sample vector
vector = np.array([1, 2, 3, 4, 5])

# Reverse the vector
reversed_vector = vector[::-1]

print(reversed_vector)


[5 4 3 2 1]


# 9.

In [11]:
# Create an array with values ranging from 0 to 8
array = np.arange(9)

# Reshape the array into a 3x3 matrix
matrix = array.reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 10.

In [12]:

# Create the array
arr = np.array([1, 2, 0, 0, 4, 0])

# Find the indices of non-zero elements
indices = np.nonzero(arr)

print(indices)


(array([0, 1, 4], dtype=int64),)


## 11.

In [13]:
 # Create a 3x3 identity matrix
identity_matrix = np.eye(3, k=0)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 12.

In [16]:
import random

# Create a 3x3x3 array with random values
array = [[[random.random() for _ in range(3)] for _ in range(3)] for _ in range(3)]

print(array)


[[[0.5319613687742569, 0.6264291219390473, 0.1956762163739182], [0.05551412545610601, 0.40074094464584864, 0.9600981077990383], [0.14258003668574493, 0.019234220556600734, 0.20203728451785008]], [[0.42954659018057917, 0.2761956581777708, 0.6213726593751309], [0.560342829816326, 0.26224375582633164, 0.8646189789620448], [0.6809239586052598, 0.3116877362832139, 0.0807562031593847]], [[0.35662334708705135, 0.38590872134540544, 0.14408384219064396], [0.507932131780235, 0.9539367253277105, 0.3153577518875481], [0.13036659383065463, 0.6931991709739849, 0.2540450803319716]]]


# 13.

In [17]:
# Create a 10x10 array with random values
array = [[random.randint(0, 100) for _ in range(10)] for _ in range(10)]

# Find the minimum and maximum values
min_value = min(min(row) for row in array)
max_value = max(max(row) for row in array)

print("Minimum value:", min_value)
print("Maximum value:", max_value)


Minimum value: 0
Maximum value: 98


# 14.

In [18]:
# Create a random vector of size 30
random_vector = [random.random() for _ in range(30)]

# Find the mean value
mean_value = sum(random_vector) / len(random_vector)

print("Mean value:", mean_value)


Mean value: 0.45136651545775414


# 15.

In [19]:
# Define the dimensions of the 2D array
rows = 5
cols = 5

# Create the 2D array with 1 on the border and 0 inside
array = [[1 if i == 0 or i == rows - 1 or j == 0 or j == cols - 1 else 0 
          for j in range(cols)] for i in range(rows)]

# Print the array
for row in array:
    print(row)


[1, 1, 1, 1, 1]
[1, 0, 0, 0, 1]
[1, 0, 0, 0, 1]
[1, 0, 0, 0, 1]
[1, 1, 1, 1, 1]


# 16.

In [20]:
# Create an existing array
existing_array = np.ones((3, 3))

# Add a border of zeros around the existing array
array_with_border = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)

print(array_with_border)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# 17.

In [21]:
print(0 * np.nan)       # nan
print(np.nan == np.nan) # False
print(np.inf > np.nan)  # False
print(np.nan - np.nan)  # nan
print(np.nan in set([np.nan]))  # True
print(0.3 == 3 * 0.1)   # False

nan
False
False
nan
True
False


# 18

In [22]:
# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Set values 1, 2, 3, 4 just below the diagonal
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 19.

In [23]:

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Set alternating values to 1
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

print(matrix)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 20.

In [7]:

# Define the shape of the array
shape = (6, 7, 8)

# Flatten index of the 100th element
flat_index = 100

# Convert the flattened index to the corresponding multi-dimensional index
indices = np.unravel_index(flat_index, shape)

print("Index (x, y, z) of the 100th element:", indices)

Index (x, y, z) of the 100th element: (1, 5, 4)


# 21.

In [8]:
# Create a 2x2 tile with 1s and 0s
tile = np.array([[1, 0], [0, 1]])

# Use tile function to repeat the tile to form an 8x8 matrix
checkerboard = np.tile(tile, (4, 4))

print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 22.

In [9]:
# Create a random 5x5 matrix
random_matrix = np.random.rand(5, 5)

# Find the maximum element in the matrix
max_value = np.max(random_matrix)

# Normalize the matrix by dividing each element by the maximum value
normalized_matrix = random_matrix / max_value

print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Original Matrix:
[[0.39723058 0.85878709 0.90444468 0.73694153 0.79766446]
 [0.95224248 0.80833098 0.0918271  0.05734079 0.29446081]
 [0.88977718 0.06043705 0.7152526  0.36169286 0.06261196]
 [0.2480474  0.20880153 0.65752953 0.20333244 0.43168571]
 [0.16260711 0.61329058 0.51253959 0.85775    0.42770404]]

Normalized Matrix:
[[0.41715276 0.90185757 0.94980501 0.77390113 0.83766948]
 [1.         0.84887096 0.09643247 0.06021659 0.30922881]
 [0.9344019  0.06346813 0.75112444 0.37983273 0.06575212]
 [0.26048764 0.21927349 0.6905064  0.2135301  0.4533359 ]
 [0.1707623  0.64404875 0.53824483 0.90076847 0.44915454]]


# 23.

In [10]:
# Define custom dtype for color as four unsigned bytes
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

# Example color (255, 128, 0, 255) - (R, G, B, A)
color = np.array((255, 128, 0, 255), dtype=color_dtype)

print("Color as a custom dtype:")
print(color)

Color as a custom dtype:
(255, 128, 0, 255)


# 24.

In [11]:
# Create a 5x3 matrix
matrix1 = np.random.random((5, 3))

# Create a 3x2 matrix
matrix2 = np.random.random((3, 2))

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

print("Result of matrix multiplication:")
print(result)

Result of matrix multiplication:
[[0.99071091 0.65518211]
 [0.52868675 0.27265775]
 [0.59484075 0.88533785]
 [0.2887588  0.78485914]
 [0.52977273 0.77265923]]


# 25.

In [12]:
# Create a sample 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Negate elements between 3 and 8 in place
arr[(arr > 3) & (arr < 8)] *= -1

print("Modified array:")
print(arr)


Modified array:
[ 1  2  3 -4 -5 -6 -7  8  9 10]


# 26.

In [15]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


# 27.

# 28.

In [17]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\My Pc\AppData\Local\Temp\ipykernel_1428\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\My Pc\AppData\Local\Temp\ipykernel_1428\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\My Pc\AppData\Local\Temp\ipykernel_1428\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

# 29.

In [18]:

def round_away_from_zero(arr):
    # Find the sign of each element
    signs = np.sign(arr)
    
    # Round each element towards positive infinity if positive
    positive_rounded = np.ceil(arr) * (signs > 0)
    
    # Round each element towards negative infinity if negative
    negative_rounded = np.floor(arr) * (signs < 0)
    
    # Combine positive and negative rounded arrays
    rounded_arr = positive_rounded + negative_rounded
    
    return rounded_arr

# Example float array
float_arr = np.array([-1.5, 2.3, -3.7, 4.8, -5.1])

# Round away from zero
rounded_arr = round_away_from_zero(float_arr)

print("Original array:")
print(float_arr)
print("\nRounded away from zero array:")
print(rounded_arr)


Original array:
[-1.5  2.3 -3.7  4.8 -5.1]

Rounded away from zero array:
[-2.  3. -4.  5. -6.]


# 30.

In [19]:

# Example arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values
common_values = np.intersect1d(array1, array2)

print("Common values:", common_values)


Common values: [3 4 5]


# 31.

In [20]:
# Ignore all NumPy warnings
np.seterr(all='ignore')

# Your code here

# Reset warnings to default behavior
np.seterr(all='warn')


{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

# 32.

In [21]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\My Pc\AppData\Local\Temp\ipykernel_1428\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

# 33.

In [22]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Get yesterday's date
yesterday = today - timedelta(days=1)

# Get tomorrow's date
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-02-14
Today: 2024-02-15
Tomorrow: 2024-02-16


# 34.

In [23]:
from datetime import datetime, timedelta

# Define the start and end dates of July 2016
start_date = datetime(2016, 7, 1)
end_date = datetime(2016, 8, 1)

# Generate all dates for July 2016
dates_july_2016 = [start_date + timedelta(days=x) for x in range((end_date - start_date).days)]

# Print the dates
for date in dates_july_2016:
    print(date)


2016-07-01 00:00:00
2016-07-02 00:00:00
2016-07-03 00:00:00
2016-07-04 00:00:00
2016-07-05 00:00:00
2016-07-06 00:00:00
2016-07-07 00:00:00
2016-07-08 00:00:00
2016-07-09 00:00:00
2016-07-10 00:00:00
2016-07-11 00:00:00
2016-07-12 00:00:00
2016-07-13 00:00:00
2016-07-14 00:00:00
2016-07-15 00:00:00
2016-07-16 00:00:00
2016-07-17 00:00:00
2016-07-18 00:00:00
2016-07-19 00:00:00
2016-07-20 00:00:00
2016-07-21 00:00:00
2016-07-22 00:00:00
2016-07-23 00:00:00
2016-07-24 00:00:00
2016-07-25 00:00:00
2016-07-26 00:00:00
2016-07-27 00:00:00
2016-07-28 00:00:00
2016-07-29 00:00:00
2016-07-30 00:00:00
2016-07-31 00:00:00


# 35.

In [26]:
import numpy as np

# Example arrays A and B
A = np.array([1, 2, 3], dtype=np.float64)
B = np.array([4, 5, 6], dtype=np.float64)

# Compute the expression ((A+B)*(-A/2)) and cast to integers
result = np.multiply(np.add(A, B), np.negative(np.divide(A, 2)))

# Store the result in array A (after casting to integers)
A[:] = result.astype(np.int32)

print("Result after computation in place:", A)


Result after computation in place: [ -2.  -7. -13.]


# 36.

In [27]:

# Generate a random array of positive numbers
random_array = np.random.rand(5) * 10  # Generate random numbers between 0 and 10

# Extract the integer part using numpy's floor function
integer_part = np.floor(random_array)

print("Method 1 (Numpy floor):", integer_part)


#Method 2
# Extract the integer part using numpy's trunc function
integer_part = np.trunc(random_array)

print("Method 2 (Numpy trunc):", integer_part)


#MEthod 3
# Extract the integer part using numpy's trunc function
integer_part = np.trunc(random_array)

print("Method 2 (Numpy trunc):", integer_part)


# Method 4
# Extract the integer part using list comprehension
integer_part = [int(x) for x in random_array]

print("Method 4 (List comprehension with int):", integer_part)


Method 1 (Numpy floor): [9. 8. 1. 6. 5.]
Method 2 (Numpy trunc): [9. 8. 1. 6. 5.]
Method 2 (Numpy trunc): [9. 8. 1. 6. 5.]
Method 4 (List comprehension with int): [9, 8, 1, 6, 5]


# 37.

In [28]:

# Create a 1D array with values ranging from 0 to 4
row_values = np.arange(5)

# Use broadcasting to create a 5x5 matrix
matrix = row_values.reshape(-1, 1) + row_values

print(matrix)


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


# 38.

In [29]:

def generate_integers():
    for i in range(10):
        yield i

# Generate integers using the generator function
integers_generator = generate_integers()

# Build an array using NumPy
array = np.fromiter(integers_generator, dtype=int)

print(array)


[0 1 2 3 4 5 6 7 8 9]


# 39.

In [31]:
# Create a vector of size 10 with values ranging from 0 to 1 (both excluded)
vector = np.linspace(0, 1, 12)[1:-1]

print(vector)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


# 40.

In [32]:
# Create a random vector of size 10
random_vector = np.random.rand(10)

# Sort the random vector
sorted_vector = np.sort(random_vector)

print("Random vector:", random_vector)
print("Sorted vector:", sorted_vector)


Random vector: [0.09328247 0.38275982 0.19730504 0.98265714 0.99466562 0.08304783
 0.17604621 0.78673532 0.64336827 0.02126177]
Sorted vector: [0.02126177 0.08304783 0.09328247 0.17604621 0.19730504 0.38275982
 0.64336827 0.78673532 0.98265714 0.99466562]


# 41.

In [33]:
# Example small array
arr = np.array([1, 2, 3, 4, 5])

# Sum using Python's built-in addition operator
result = np.sum(arr)

print("Sum using np.sum:", result)


Sum using np.sum: 15


# 42.

In [34]:
# Generate two random arrays A and B
A = np.random.rand(5)
B = np.random.rand(5)

# Check if A and B are equal element-wise
are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)
print("Are A and B equal?", are_equal)


Array A: [0.73482564 0.49583533 0.10802369 0.83867696 0.87716934]
Array B: [0.01842611 0.39319626 0.72223935 0.75474126 0.28811553]
Are A and B equal? False


# 43.

In [35]:
# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Make the array read-only
arr.flags.writeable = False

# Try to modify the array (this will raise an error)
try:
    arr[0] = 10
except ValueError as e:
    print("Error:", e)


Error: assignment destination is read-only


# 44.

In [37]:
# Generate a random 10x2 matrix representing cartesian coordinates
cartesian_coordinates = np.random.rand(10, 2)

# Extract x and y coordinates
x = cartesian_coordinates[:, 0]
y = cartesian_coordinates[:, 1]

# Calculate radius (r) and angle (theta) in radians
r = np.linalg.norm(cartesian_coordinates, axis=1)
theta = np.arctan2(y, x)

# Convert angle from radians to degrees
theta_degrees = np.degrees(theta)

# Combine radius and angle to get polar coordinates
polar_coordinates = np.column_stack((r, theta_degrees))

print("Cartesian Coordinates:")
print(cartesian_coordinates)
print("\nPolar Coordinates:")
print(polar_coordinates)


Cartesian Coordinates:
[[0.9387614  0.16034439]
 [0.59590635 0.20387607]
 [0.17311816 0.05521599]
 [0.02094296 0.82407752]
 [0.53675357 0.17536136]
 [0.4666515  0.84099217]
 [0.86100955 0.08480086]
 [0.19152934 0.54893504]
 [0.70389497 0.97690394]
 [0.57920983 0.20506921]]

Polar Coordinates:
[[ 0.9523567   9.69282252]
 [ 0.6298173  18.88723816]
 [ 0.18171049 17.69006881]
 [ 0.8243436  88.54420853]
 [ 0.56467336 18.09259822]
 [ 0.96178555 60.97489011]
 [ 0.86517549  5.62492255]
 [ 0.581389   70.76557088]
 [ 1.20408032 54.22587242]
 [ 0.61444073 19.49650578]]


# 45.

In [38]:
# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random vector:", random_vector)


Random vector: [0.69289031 0.65048966 0.72840493 0.57361313 0.4967526  0.
 0.80814599 0.48410328 0.22328691 0.66103851]


# 46.

In [39]:
# Define the number of points along each axis
n_points = 10

# Create a grid of x and y coordinates
x_values = np.linspace(0, 1, n_points)
y_values = np.linspace(0, 1, n_points)
x_grid, y_grid = np.meshgrid(x_values, y_values)

# Create a structured array with x and y coordinates
structured_array = np.empty((n_points*n_points,), dtype=[('x', float), ('y', float)])
structured_array['x'] = x_grid.flatten()
structured_array['y'] = y_grid.flatten()

print("Structured array:")
print(structured_array)


Structured array:
[(0.        , 0.        ) (0.11111111, 0.        )
 (0.22222222, 0.        ) (0.33333333, 0.        )
 (0.44444444, 0.        ) (0.55555556, 0.        )
 (0.66666667, 0.        ) (0.77777778, 0.        )
 (0.88888889, 0.        ) (1.        , 0.        )
 (0.        , 0.11111111) (0.11111111, 0.11111111)
 (0.22222222, 0.11111111) (0.33333333, 0.11111111)
 (0.44444444, 0.11111111) (0.55555556, 0.11111111)
 (0.66666667, 0.11111111) (0.77777778, 0.11111111)
 (0.88888889, 0.11111111) (1.        , 0.11111111)
 (0.        , 0.22222222) (0.11111111, 0.22222222)
 (0.22222222, 0.22222222) (0.33333333, 0.22222222)
 (0.44444444, 0.22222222) (0.55555556, 0.22222222)
 (0.66666667, 0.22222222) (0.77777778, 0.22222222)
 (0.88888889, 0.22222222) (1.        , 0.22222222)
 (0.        , 0.33333333) (0.11111111, 0.33333333)
 (0.22222222, 0.33333333) (0.33333333, 0.33333333)
 (0.44444444, 0.33333333) (0.55555556, 0.33333333)
 (0.66666667, 0.33333333) (0.77777778, 0.33333333)
 (0.88888889,

# 47.

In [40]:
# Example arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Construct the Cauchy matrix C
C = 1 / (X[:, np.newaxis] - Y)

print("Cauchy matrix C:")
print(C)


Cauchy matrix C:
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


# 48.

In [41]:
# Integer types
print("Integer types:")
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__}: Min={info.min}, Max={info.max}")

# Unsigned integer types
print("\nUnsigned integer types:")
for dtype in [np.uint8, np.uint16, np.uint32, np.uint64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__}: Min={info.min}, Max={info.max}")

# Floating-point types
print("\nFloating-point types:")
for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype.__name__}: Min={info.min}, Max={info.max}")


Integer types:
int8: Min=-128, Max=127
int16: Min=-32768, Max=32767
int32: Min=-2147483648, Max=2147483647
int64: Min=-9223372036854775808, Max=9223372036854775807

Unsigned integer types:
uint8: Min=0, Max=255
uint16: Min=0, Max=65535
uint32: Min=0, Max=4294967295
uint64: Min=0, Max=18446744073709551615

Floating-point types:
float16: Min=-65504.0, Max=65504.0
float32: Min=-3.4028234663852886e+38, Max=3.4028234663852886e+38
float64: Min=-1.7976931348623157e+308, Max=1.7976931348623157e+308


# 49.

In [42]:
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Print all the values of the array using a loop
for element in arr:
    print(element)


1
2
3
4
5


# 50.

In [43]:
# Example vector
vector = np.array([1, 3, 5, 7, 9])

# Given scalar
scalar = 4

# Find the index of the closest value
closest_index = np.abs(vector - scalar).argmin()

# Closest value
closest_value = vector[closest_index]

print("Vector:", vector)
print("Scalar:", scalar)
print("Closest value:", closest_value)


Vector: [1 3 5 7 9]
Scalar: 4
Closest value: 3


# 51.

In [44]:
# Define the data type for the structured array
dtype = [('position', [('x', float), ('y', float)]), ('color', [('r', int), ('g', int), ('b', int)])]

# Create a structured array with specified data type
structured_array = np.array([((1.0, 2.0), (255, 0, 0)), ((3.0, 4.0), (0, 255, 0)), ((5.0, 6.0), (0, 0, 255))], dtype=dtype)

print(structured_array)


False

# 52.

In [48]:

# Generate random vector with shape (100, 2) representing coordinates
coordinates = np.random.rand(100, 2)

# Calculate point-by-point distances
distances = np.linalg.norm(coordinates[:, np.newaxis] - coordinates, axis=-1)

print(distances)


[[0.         0.71995752 0.67316182 ... 0.34950283 0.55213982 0.41067231]
 [0.71995752 0.         0.16528066 ... 0.3714061  0.23523861 0.65459041]
 [0.67316182 0.16528066 0.         ... 0.33460514 0.31977606 0.70629808]
 ...
 [0.34950283 0.3714061  0.33460514 ... 0.         0.24509797 0.42327226]
 [0.55213982 0.23523861 0.31977606 ... 0.24509797 0.         0.41989734]
 [0.41067231 0.65459041 0.70629808 ... 0.42327226 0.41989734 0.        ]]


# 53.

In [49]:
# Create a float array
float_array = np.array([1.5, 2.7, 3.8, 4.2], dtype=np.float32)

# Convert the float array to an integer array in place
float_array = float_array.astype(np.int32)

print(float_array)


[1 2 3 4]


# 54.

# 55.

In [52]:
# Create a numpy array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Enumerate over the array
for index, value in np.ndenumerate(arr):
    print(index, value)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


# 56.

In [53]:
def gaussian(x, y, sigma):
    return np.exp(-(x**2 + y**2) / (2 * sigma**2))

# Define the parameters
size = 11  # Size of the array
sigma = 2  # Standard deviation of the Gaussian

# Generate the coordinates
x = np.linspace(-size // 2, size // 2, size)
y = np.linspace(-size // 2, size // 2, size)

# Create a meshgrid of the coordinates
X, Y = np.meshgrid(x, y)

# Calculate the Gaussian values
gaussian_array = gaussian(X, Y, sigma)

print(gaussian_array)


[[1.23409804e-04 5.52393447e-04 1.82714617e-03 4.46605415e-03
  8.06678714e-03 1.07672086e-02 1.06201727e-02 7.74080184e-03
  4.16932970e-03 1.65948162e-03 4.88095244e-04]
 [5.52393447e-04 2.47256304e-03 8.17847153e-03 1.99904624e-02
  3.61076689e-02 4.81949999e-02 4.75368538e-02 3.46485293e-02
  1.86622969e-02 7.42798986e-03 2.18475846e-03]
 [1.82714617e-03 8.17847153e-03 2.70518469e-02 6.61222485e-02
  1.19432968e-01 1.59414110e-01 1.57237166e-01 1.14606587e-01
  6.17290890e-02 2.45694863e-02 7.22650328e-03]
 [4.46605415e-03 1.99904624e-02 6.61222485e-02 1.61621192e-01
  2.91927440e-01 3.89652485e-01 3.84331430e-01 2.80130420e-01
  1.50883087e-01 6.00546679e-02 1.76635868e-02]
 [8.06678714e-03 3.61076689e-02 1.19432968e-01 2.91927440e-01
  5.27292424e-01 7.03807780e-01 6.94196651e-01 5.05984117e-01
  2.72531793e-01 1.08473432e-01 3.19047620e-02]
 [1.07672086e-02 4.81949999e-02 1.59414110e-01 3.89652485e-01
  7.03807780e-01 9.39413063e-01 9.26584531e-01 6.75366346e-01
  3.63763990e-01

# 57.

In [54]:

def randomly_place_elements(array, p, value):
    # Get the size of the array
    rows, cols = array.shape
    
    # Calculate the total number of elements
    total_elements = rows * cols
    
    # Calculate the number of elements to place
    num_elements_to_place = int(total_elements * p)
    
    # Generate random indices
    indices = np.random.choice(total_elements, num_elements_to_place, replace=False)
    
    # Reshape the indices to match the array shape
    row_indices = indices // cols
    col_indices = indices % cols
    
    # Assign the value to the random indices
    array[row_indices, col_indices] = value
    
    return array

# Example usage
rows, cols = 5, 5  # Size of the 2D array
p = 0.2  # Probability of placing elements
value = 1  # Value to place

# Create a 2D array
array = np.zeros((rows, cols))

# Randomly place elements
array = randomly_place_elements(array, p, value)

print(array)


[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


# 58.

In [55]:
# Example matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the mean of each row from the original matrix
matrix_normalized = matrix - row_means

print(matrix_normalized)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 59.

In [56]:

# Example array
array = np.array([[1, 4, 3],
                  [6, 2, 8],
                  [5, 7, 9]])

# Sort the array by the nth column (n=1 in this example)
n = 1
sorted_indices = np.argsort(array[:, n])

# Use the sorted indices to rearrange the rows of the array
sorted_array = array[sorted_indices]

print("Original array:")
print(array)
print("\nSorted array by the nth column:")
print(sorted_array)


Original array:
[[1 4 3]
 [6 2 8]
 [5 7 9]]

Sorted array by the nth column:
[[6 2 8]
 [1 4 3]
 [5 7 9]]


# 60.

In [57]:
# Example 2D array
array = np.array([[1, 0, 3],
                  [0, 0, 0],
                  [4, 0, 6]])

# Check if any column contains only null values
null_columns = np.all(array == array[0, :], axis=0)

print("Columns with null values:", null_columns)


Columns with null values: [False  True False]


# 61.

In [60]:
# Example array
array = np.array([1, 3, 5, 7, 9])

# Given value
given_value = 6

# Find the index of the nearest value
nearest_index = np.abs(array - given_value).argmin()

# Nearest value
nearest_value = array[nearest_index]

print("Nearest value:", nearest_value)


Nearest value: 5


# 62.

In [61]:
# Define the arrays
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5], [6]])

# Initialize the sum
total_sum = 0

# Iterate over the elements and compute the sum
iterator1 = np.nditer(array1)
iterator2 = np.nditer(array2)

for x, y in zip(iterator1, iterator2):
    total_sum += (x + y)

print("Sum of the arrays:", total_sum)


Sum of the arrays: 21


# 63.

In [62]:
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=None):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, 'name', None)

# Example usage:
array_data = np.array([[1, 2, 3], [4, 5, 6]])
my_array = NamedArray(array_data, name="My Array")

print("Name of the array:", my_array.name)
print("Array:")
print(my_array)


Name of the array: My Array
Array:
[[1 2 3]
 [4 5 6]]


# 64.

In [63]:
# Given vectors
vector1 = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 1, 3, 3, 4, 4])  # Example indices (with repetitions)

# Create a mask to handle repeated indices
unique_indices, unique_indices_counts = np.unique(indices, return_counts=True)
mask = np.zeros_like(vector1, dtype=bool)
mask[unique_indices] = True

# Add 1 to elements indexed by unique indices
vector1[mask] += 1

print("Modified vector1:", vector1)


Modified vector1: [2 3 3 5 6]


# 65.

In [65]:
import numpy as np

# Given vector X, index list I, and array F
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 2, 0, 1, 2])  # Example index list
F = np.zeros(3)  # Initialize array F with zeros

# Accumulate elements of X into F based on the index list I
np.add.at(F, I, X)

print("Accumulated array F:", F)


ValueError: array is not broadcastable to correct shape

# 66.

In [66]:
# Example image array
image = np.random.randint(0, 256, size=(10, 10, 3), dtype=np.uint8)  # Example image (ubyte)

# Reshape the image into a 2D array (pixels, color channels)
pixels = image.reshape(-1, 3)

# Find unique colors
unique_colors = np.unique(pixels, axis=0)

# Number of unique colors
num_unique_colors = len(unique_colors)

print("Number of unique colors:", num_unique_colors)


Number of unique colors: 100


# 67.

In [67]:
# Example four-dimensional array
array_4d = np.random.randint(0, 10, size=(2, 3, 4, 5))

# Get the sum over the last two axes at once
sum_last_two_axes = np.sum(array_4d, axis=(-2, -1))

print("Sum over the last two axes:")
print(sum_last_two_axes)


Sum over the last two axes:
[[ 86  82  67]
 [100  62  71]]


# 68.

In [68]:
# Example one-dimensional vector D and subset indices vector S
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  # Example vector
S = np.array([0, 0, 1, 1, 1, 2, 2, 2, 3, 3])   # Example subset indices vector

# Find unique subset indices
unique_indices = np.unique(S)

# Compute means of subsets of D using subset indices
subset_means = np.array([np.mean(D[S == idx]) for idx in unique_indices])

print("Subset indices:", unique_indices)
print("Subset means:", subset_means)


Subset indices: [0 1 2 3]
Subset means: [1.5 4.  7.  9.5]


# 69.

In [69]:
# Example matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Compute the dot product of A and B
dot_product = np.dot(A, B)

# Get the diagonal elements of the dot product
diagonal_elements = np.einsum('ii->i', dot_product)

print("Diagonal of the dot product:")
print(diagonal_elements)


Diagonal of the dot product:
[30 69 90]


# 70.

In [70]:
# Initial vector
initial_vector = np.array([1, 2, 3, 4, 5])

# Number of consecutive zeros to insert between each value
num_zeros = 3

# Initialize the new vector with zeros
new_vector_length = len(initial_vector) + (len(initial_vector) - 1) * num_zeros
new_vector = np.zeros(new_vector_length, dtype=initial_vector.dtype)

# Insert values from the initial vector and zeros at the desired intervals
new_vector[::num_zeros + 1] = initial_vector

print("New vector with zeros interleaved:")
print(new_vector)


New vector with zeros interleaved:
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


# 71.

In [71]:
import numpy as np

# Create a 3D array of dimension (5, 5, 3)
array_3d = np.random.randint(1, 10, size=(5, 5, 3))

# Create a 2D array with dimensions (5, 5)
array_2d = np.random.randint(1, 10, size=(5, 5))

# Multiply the 3D array by the 2D array
result = array_3d * array_2d[:, :, np.newaxis]

print("Resulting shape:", result.shape)


Resulting shape: (5, 5, 3)


# 72.

In [72]:
# Create a sample 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Define the indices of the rows you want to swap
row_index1 = 0
row_index2 = 2

# Swap the rows
array[[row_index1, row_index2]] = array[[row_index2, row_index1]]

print("Array after swapping rows:")
print(array)


Array after swapping rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 73.

In [73]:
# Example set of 10 triplets describing 10 triangles
triplets = [
    [(0, 0), (1, 0), (0, 1)],  # Triangle 1
    [(1, 0), (1, 1), (0, 1)],  # Triangle 2
    [(1, 1), (2, 1), (1, 2)],  # Triangle 3
    # Add more triangles here...
]

# Function to get line segments from a triangle
def get_line_segments(triangle):
    segments = set()
    for i in range(3):
        for j in range(i + 1, 3):
            segment = (triangle[i], triangle[j])
            segments.add(tuple(sorted(segment)))  # Ensure consistent ordering
    return segments

# Find unique line segments from all triangles
unique_segments = set()
for triangle in triplets:
    segments = get_line_segments(triangle)
    unique_segments.update(segments)

print("Unique line segments:")
for segment in unique_segments:
    print(segment)


Unique line segments:
((1, 1), (2, 1))
((1, 0), (1, 1))
((0, 1), (1, 1))
((0, 0), (0, 1))
((0, 1), (1, 0))
((1, 2), (2, 1))
((0, 0), (1, 0))
((1, 1), (1, 2))


# 74.

In [74]:

def reconstruct_array(bincount_array):
    indices = np.arange(len(bincount_array))  # Generate indices
    return np.repeat(indices, bincount_array)  # Repeat indices based on bincount

# Example sorted array representing bincount
C = np.array([0, 1, 1, 3, 0, 2, 0, 1, 0, 1])

# Reconstruct the original array
A = reconstruct_array(C)

print("Reconstructed array A:", A)
print("Bincount of A:", np.bincount(A))
print("Original bincount array C:", C)


Reconstructed array A: [1 2 3 3 3 5 5 7 9]
Bincount of A: [0 1 1 3 0 2 0 1 0 1]
Original bincount array C: [0 1 1 3 0 2 0 1 0 1]


# 75.

In [75]:
def sliding_window_average(array, window_size):
    # Pad the array to handle edge cases
    padded_array = np.pad(array, (window_size//2, window_size//2), mode='edge')
    
    # Compute the rolling sum using a 1D convolution
    window = np.ones(window_size) / window_size
    rolling_sum = np.convolve(padded_array, window, mode='valid')
    
    # Compute the number of elements in each window
    counts = np.convolve(np.ones_like(padded_array), window, mode='valid')
    
    # Compute the average
    averages = rolling_sum / counts
    
    return averages

# Example input array
input_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Window size
window_size = 3

# Compute sliding window averages
result = sliding_window_average(input_array, window_size)

print("Input array:", input_array)
print("Sliding window averages with window size", window_size, ":", result)


Input array: [ 1  2  3  4  5  6  7  8  9 10]
Sliding window averages with window size 3 : [1.33333333 2.         3.         4.         5.         6.
 7.         8.         9.         9.66666667]


# 76.

In [76]:
# Example one-dimensional array Z
Z = np.array([1, 2, 3, 4, 5, 6, 7])

# Number of elements in each row
num_elements = 3

# Create the two-dimensional array
num_rows = len(Z) - num_elements + 1
result = np.empty((num_rows, num_elements), dtype=Z.dtype)

# Fill in the array row by row
for i in range(num_rows):
    result[i] = Z[i:i+num_elements]

print("Two-dimensional array:")
print(result)


Two-dimensional array:
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


# 77.

In [77]:
# Negate a boolean
boolean_var = True
boolean_var = ~boolean_var  # Negate the boolean
print("Negated boolean:", boolean_var)

# Change the sign of a float
float_var = 3.5
float_var = -float_var  # Change the sign of the float
print("Float with changed sign:", float_var)


Negated boolean: -2
Float with changed sign: -3.5


C:\Users\My Pc\AppData\Local\Temp\ipykernel_1428\529350697.py:3: DeprecationWarning: Bitwise inversion '~' on bool is deprecated. This returns the bitwise inversion of the underlying int object and is usually not what you expect from negating a bool. Use the 'not' operator for boolean negation or ~int(x) if you really want the bitwise inversion of the underlying int.
  boolean_var = ~boolean_var  # Negate the boolean


# 78.

In [79]:
def distance_point_to_line_segment(P0, P1, p):
    # Compute direction vectors
    v = P1 - P0
    
    # Compute vectors from P0 to p
    w = p - P0
    
    # Compute dot products
    c1 = np.dot(w, v)
    c2 = np.dot(v, v)
    
    # Compute projection parameter
    b = c1 / c2
    
    # Clamp parameter b to [0, 1]
    b = np.clip(b, 0, 1)
    
    # Compute projected point
    Pb = P0 + b * v
    
    # Compute distance
    distance = np.linalg.norm(p - Pb)
    
    return distance

# Example points
P0 = np.array([[1, 1], [2, 3], [4, 2]])  # Starting points of line segments
P1 = np.array([[4, 5], [5, 7], [7, 6]])  # Ending points of line segments
p = np.array([3, 2])  # Point to compute distance to

# Compute distances from p to each line segment
distances = [distance_point_to_line_segment(p0, p1, p) for p0, p1 in zip(P0, P1)]

print("Distances to each line segment:", distances)


Distances to each line segment: [0.9999999999999999, 1.4142135623730951, 1.0]


# 79.

In [81]:
def distance_point_to_line_segment(P0, P1, p):
    # Compute direction vectors
    v = P1 - P0
    
    # Compute vectors from P0 to p
    w = p - P0
    
    # Compute dot products
    c1 = np.dot(w, v)
    c2 = np.dot(v, v)
    
    # Compute projection parameter
    b = c1 / c2
    
    # Clamp parameter b to [0, 1]
    b = np.clip(b, 0, 1)
    
    # Compute projected point
    Pb = P0 + b * v
    
    # Compute distance
    distance = np.linalg.norm(p - Pb)
    
    return distance

def distance_points_to_lines(P0, P1, P):
    distances = []
    for p in P:
        # Compute distances from p to each line segment
        distances.append([distance_point_to_line_segment(p0, p1, p) for p0, p1 in zip(P0, P1)])
    return np.array(distances)

# Example points
P0 = np.array([[1, 1], [2, 3], [4, 2]])  # Starting points of line segments
P1 = np.array([[4, 5], [5, 7], [7, 6]])  # Ending points of line segments
P = np.array([[3, 2], [6, 4], [2, 5], [8, 7]])  # Points to compute distance to

# Compute distances from each point to each line segment
distances = distance_points_to_lines(P0, P1, P)

print("Distances from each point to each line segment:")
print(distances)


Distances from each point to each line segment:
[[1.         1.41421356 1.        ]
 [2.23606798 2.6        0.4       ]
 [1.6        1.2        3.4       ]
 [4.47213595 3.         1.41421356]]


# 80.

In [84]:
import numpy as np

def extract_subpart(array, center, shape, fill_value=0):
    # Convert tuples to NumPy arrays
    center = np.array(center)
    shape = np.array(shape)
    
    # Determine the indices for the subpart
    half_shape = shape // 2
    start_index = center - half_shape
    end_index = start_index + shape
    
    # Pad the indices to handle edge cases
    start_index = np.maximum(start_index, 0)
    end_index = np.minimum(end_index, np.array(array.shape))
    
    # Extract the subpart from the original array
    subpart = array[start_index[0]:end_index[0], start_index[1]:end_index[1]]
    
    # Pad the subpart if necessary
    padded_subpart = np.full(shape, fill_value, dtype=array.dtype)
    pad_start = half_shape - (center - start_index)
    pad_end = shape - subpart.shape - pad_start
    padded_subpart[pad_start[0]:pad_start[0]+subpart.shape[0], 
                   pad_start[1]:pad_start[1]+subpart.shape[1]] = subpart
    
    return padded_subpart

# Example array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Example center and shape
center = (1, 2)
shape = (3, 3)

# Extract subpart
subpart = extract_subpart(array, center, shape, fill_value=0)

print("Original array:")
print(array)
print("Subpart centered at", center, "with shape", shape, ":")
print(subpart)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Subpart centered at (1, 2) with shape (3, 3) :
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


# 81.

In [85]:
# Define the array Z
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# Define the length of each subarray
subarray_length = 4

# Calculate the number of subarrays
num_subarrays = len(Z) - subarray_length + 1

# Generate the array R
R = np.array([Z[i:i+subarray_length] for i in range(num_subarrays)])

print("Array R:")
print(R)


Array R:
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


# 82.

In [86]:
import numpy as np

# Example matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print("Rank of the matrix:", rank)


Rank of the matrix: 2


# 83.

In [87]:
# Example array
arr = np.array([1, 2, 3, 2, 2, 1, 3, 3, 3])

# Find the most frequent value
most_frequent_value = np.argmax(np.bincount(arr))

print("Most frequent value in the array:", most_frequent_value)


Most frequent value in the array: 3


# 84.

In [88]:
# Generate a random 10x10 matrix
matrix = np.random.randint(0, 10, size=(10, 10))

# Extract contiguous 3x3 blocks
blocks = []
for i in range(8):  # Iterate over rows
    for j in range(8):  # Iterate over columns
        block = matrix[i:i+3, j:j+3]  # Extract 3x3 block
        blocks.append(block)

# Convert the list of blocks to a NumPy array
blocks_array = np.array(blocks)

print("Contiguous 3x3 blocks extracted from the matrix:")
print(blocks_array)


Contiguous 3x3 blocks extracted from the matrix:
[[[3 1 4]
  [0 1 1]
  [2 2 0]]

 [[1 4 6]
  [1 1 0]
  [2 0 7]]

 [[4 6 5]
  [1 0 2]
  [0 7 1]]

 [[6 5 7]
  [0 2 2]
  [7 1 9]]

 [[5 7 0]
  [2 2 0]
  [1 9 5]]

 [[7 0 3]
  [2 0 8]
  [9 5 7]]

 [[0 3 9]
  [0 8 9]
  [5 7 2]]

 [[3 9 0]
  [8 9 4]
  [7 2 5]]

 [[0 1 1]
  [2 2 0]
  [0 9 3]]

 [[1 1 0]
  [2 0 7]
  [9 3 6]]

 [[1 0 2]
  [0 7 1]
  [3 6 1]]

 [[0 2 2]
  [7 1 9]
  [6 1 1]]

 [[2 2 0]
  [1 9 5]
  [1 1 7]]

 [[2 0 8]
  [9 5 7]
  [1 7 1]]

 [[0 8 9]
  [5 7 2]
  [7 1 2]]

 [[8 9 4]
  [7 2 5]
  [1 2 6]]

 [[2 2 0]
  [0 9 3]
  [9 4 8]]

 [[2 0 7]
  [9 3 6]
  [4 8 9]]

 [[0 7 1]
  [3 6 1]
  [8 9 1]]

 [[7 1 9]
  [6 1 1]
  [9 1 9]]

 [[1 9 5]
  [1 1 7]
  [1 9 1]]

 [[9 5 7]
  [1 7 1]
  [9 1 4]]

 [[5 7 2]
  [7 1 2]
  [1 4 4]]

 [[7 2 5]
  [1 2 6]
  [4 4 1]]

 [[0 9 3]
  [9 4 8]
  [6 7 2]]

 [[9 3 6]
  [4 8 9]
  [7 2 2]]

 [[3 6 1]
  [8 9 1]
  [2 2 6]]

 [[6 1 1]
  [9 1 9]
  [2 6 1]]

 [[1 1 7]
  [1 9 1]
  [6 1 0]]

 [[1 7 1]
  [9 1 4]
  [

# 85.

In [90]:
class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj

    def __setitem__(self, index, value):
        i, j = index
        super().__setitem__((i, j), value)  # Set the value at index [i, j]
        super().__setitem__((j, i), value)  # Also set the value at index [j, i]

# Example usage
Z = SymmetricArray(np.zeros((3, 3)))
Z[0, 1] = 5
print(Z)


[[0. 5. 0.]
 [5. 0. 0.]
 [0. 0. 0.]]


# 86.

In [94]:
def sum_of_matrix_vector_products(matrices, vectors):
    # Ensure matrices and vectors have compatible shapes
    assert matrices.shape[0] == vectors.shape[0]
    assert matrices.shape[1] == matrices.shape[2] == vectors.shape[1]
    
    # Compute the sum of matrix-vector products
    result = np.sum(np.matmul(matrices, vectors), axis=0)
    
    return result

# Example matrices and vectors
p = 3  # Number of matrices and vectors
n = 2  # Shape of matrices and vectors

matrices = np.random.rand(p, n, n)  # Generate random matrices
vectors = np.random.rand(p, n, 1)   # Generate random vectors

# Compute the sum of matrix-vector products
result = sum_of_matrix_vector_products(matrices, vectors)

print("Sum of matrix-vector products:")
print(result)


Sum of matrix-vector products:
[[1.72493617]
 [2.28092509]]


# 87.

In [95]:

# Example 16x16 array
array = np.random.randint(0, 10, size=(16, 16))

# Reshape the array into a 4D array with block size 4x4
block_shape = (4, 4)
blocks = array.reshape(array.shape[0] // block_shape[0], block_shape[0], 
                       array.shape[1] // block_shape[1], block_shape[1])

# Sum along the last two axes to get the block sum
block_sum = np.sum(blocks, axis=(-2, -1))

print("Block sum:")
print(block_sum)


Block sum:
[[58 75 76 70]
 [49 80 66 77]
 [44 74 76 67]
 [69 62 92 70]]


# 88.

In [97]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

def evolve(grid):
    neighbor_count = sum(np.roll(np.roll(grid, i, axis=0), j, axis=1)
                         for i in (-1, 0, 1) for j in (-1, 0, 1) if (i != 0 or j != 0))
    new_grid = (neighbor_count == 3) | (grid & (neighbor_count == 2))
    return new_grid.astype(int)

# Initialize the grid with random values
grid_size = 100
grid = np.random.choice([0, 1], size=(grid_size, grid_size), p=[0.9, 0.1])

# Create animation
fig, ax = plt.subplots()
img = ax.imshow(grid, interpolation='nearest', cmap='gray')

def update(frame):
    global grid
    grid = evolve(grid)
    img.set_array(grid)
    return img,

ani = animation.FuncAnimation(fig, update, frames=100, interval=50)
plt.show()


ModuleNotFoundError: No module named 'matplotlib'

# 89.

In [98]:

def n_largest_values(array, n):
    # Get indices of n largest values
    indices = np.argpartition(array, -n)[-n:]
    
    # Sort the indices based on the values
    sorted_indices = indices[np.argsort(array[indices])]
    
    # Extract the n largest values and return
    return sorted_indices, array[sorted_indices]

# Example array
array = np.array([1, 3, 2, 5, 4])

# Get the 3 largest values and their indices
n = 3
indices, values = n_largest_values(array, n)

print("Indices of the {} largest values:".format(n), indices)
print("Values of the {} largest values:".format(n), values)


Indices of the 3 largest values: [1 4 3]
Values of the 3 largest values: [3 4 5]


# 90.

In [99]:
from itertools import product

def cartesian_product(*vectors):
    return list(product(*vectors))

# Example vectors
vector1 = [1, 2]
vector2 = ['a', 'b', 'c']
vector3 = [True, False]

# Calculate the cartesian product
result = cartesian_product(vector1, vector2, vector3)

print("Cartesian product:")
for item in result:
    print(item)


Cartesian product:
(1, 'a', True)
(1, 'a', False)
(1, 'b', True)
(1, 'b', False)
(1, 'c', True)
(1, 'c', False)
(2, 'a', True)
(2, 'a', False)
(2, 'b', True)
(2, 'b', False)
(2, 'c', True)
(2, 'c', False)


# 91.

In [100]:
# Regular array
regular_array = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

# Create record array
record_array = np.core.records.fromarrays(regular_array.T,
                                           names='col1, col2, col3')

print("Record array:")
print(record_array)


Record array:
[(1, 2, 3) (4, 5, 6) (7, 8, 9)]


# 92.

In [101]:
# Method 1: Using np.power()
Z_cube_1 = np.power(Z, 3)

# Method 2: Using the ** operator
Z_cube_2 = Z ** 3

# Method 3: Using np.multiply() twice
Z_cube_3 = np.multiply(np.multiply(Z, Z), Z)


# 93.

In [104]:
# Example arrays
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [1, 3, 2],
              [4, 6, 5],
              [9, 7, 8],
              [2, 1, 3],
              [5, 6, 4]])

B = np.array([[1, 2],
              [3, 4]])

# Sort the rows of B
sorted_B = np.sort(B, axis=1)

# Sort the rows of A
sorted_A = np.sort(A, axis=1)

# Reshape B to have the same number of dimensions as sorted_A
reshaped_B = sorted_B[:, :, np.newaxis]

# Check if any row of A contains elements of each row of B
rows_containing_B = np.all(sorted_A[:, np.newaxis, :] == reshaped_B, axis=-1).any(axis=-1)

# Get the rows of A that contain elements of each row of B
result = A[rows_containing_B]

print("Rows of A containing elements of each row of B:")
print(result)


ValueError: operands could not be broadcast together with shapes (8,1,3) (2,2,1) 

# 94.

In [105]:
# Example 10x3 matrix
matrix = np.array([[1, 2, 3],
                   [2, 2, 2],
                   [4, 5, 6],
                   [7, 7, 7],
                   [8, 8, 9],
                   [2, 2, 3],
                   [4, 4, 4],
                   [5, 5, 5],
                   [6, 7, 8],
                   [9, 9, 9]])

# Find rows with unequal values
unequal_rows = np.array([any(np.unique(row).size != 1) for row in matrix])

# Extract rows with unequal values
result = matrix[unequal_rows]

print("Rows with unequal values:")
print(result)


Rows with unequal values:
[[1 2 3]
 [4 5 6]
 [8 8 9]
 [2 2 3]
 [6 7 8]]


# 95.

In [106]:

def int_to_binary_matrix(vector):
    # Determine the number of bits needed to represent the maximum value in the vector
    max_value = np.max(vector)
    num_bits = int(np.ceil(np.log2(max_value + 1)))
    
    # Convert each integer to binary representation
    binary_matrix = ((vector[:, None] & (1 << np.arange(num_bits))) > 0).astype(int)
    
    return binary_matrix

# Example vector
vector = np.array([2, 5, 7, 10])

# Convert to binary matrix
binary_matrix = int_to_binary_matrix(vector)

print("Binary matrix representation:")
print(binary_matrix)


Binary matrix representation:
[[0 1 0 0]
 [1 0 1 0]
 [1 1 1 0]
 [0 1 0 1]]


# 96

In [107]:
def extract_unique_rows(array):
    # Convert the array to a contiguous array
    array = np.ascontiguousarray(array)
    # Get the unique rows
    unique_rows, indices = np.unique(array, axis=0, return_index=True)
    return unique_rows

# Example two-dimensional array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [1, 2, 3],
                  [7, 8, 9],
                  [4, 5, 6],
                  [10, 11, 12]])

# Extract unique rows
unique_rows = extract_unique_rows(array)

print("Unique rows:")
print(unique_rows)


Unique rows:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# 97.

In [108]:
# Example vectors A and B
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Inner product
inner_product = np.einsum('i,i->', A, B)
print("Inner product:", inner_product)

# Outer product
outer_product = np.einsum('i,j->ij', A, B)
print("Outer product:")
print(outer_product)

# Sum
sum_A = np.einsum('i->', A)
print("Sum of A:", sum_A)

# Element-wise multiplication
elementwise_mult = np.einsum('i,i->i', A, B)
print("Element-wise multiplication:")
print(elementwise_mult)


Inner product: 32
Outer product:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum of A: 6
Element-wise multiplication:
[ 4 10 18]


# 98.

In [110]:
def equidistant_samples(X, Y, num_samples):
    # Compute the Euclidean distance between consecutive points
    distances = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
    
    # Compute the total length of the path
    total_length = np.sum(distances)
    
    # Compute the length of each segment
    segment_length = total_length / (num_samples - 1)
    
    # Initialize arrays to store equidistant samples
    equidistant_X = np.zeros(num_samples)
    equidistant_Y = np.zeros(num_samples)
    
    # Initialize variables for interpolation
    current_distance = 0
    current_index = 0
    
    # Interpolate between points to obtain equidistant samples
    for i in range(num_samples):
        # Find the segment containing the current equidistant sample
        while current_distance < i * segment_length and current_index < len(distances):
            current_distance += distances[current_index]
            current_index += 1
        
        # Handle the case when current_index reaches the end of the distances array
        if current_index == len(distances):
            equidistant_X[i] = X[-1]
            equidistant_Y[i] = Y[-1]
        else:
            # Interpolate between consecutive points in the segment
            t = (i * segment_length - (current_distance - distances[current_index])) / distances[current_index]
            equidistant_X[i] = (1 - t) * X[current_index - 1] + t * X[current_index]
            equidistant_Y[i] = (1 - t) * Y[current_index - 1] + t * Y[current_index]
    
    return equidistant_X, equidistant_Y

# Example vectors describing the path
X = np.array([0, 1, 3, 6, 9])
Y = np.array([0, 2, 4, 5, 6])

# Number of equidistant samples
num_samples = 10

# Get equidistant samples
equidistant_X, equidistant_Y = equidistant_samples(X, Y, num_samples)

print("Equidistant samples (X):", equidistant_X)
print("Equidistant samples (Y):", equidistant_Y)


Equidistant samples (X): [0.         0.65683474 1.39761382 2.1979547  2.99829559 4.1979547
 5.39846603 9.         9.         9.        ]
Equidistant samples (Y): [0.         1.31366948 2.39761382 3.1979547  3.99829559 4.39931823
 4.79948868 6.         6.         6.        ]


# 99.

In [111]:
def select_multinomial_rows(X, n):
    # Check if each element in X is an integer
    is_integer = np.all(np.equal(np.mod(X, 1), 0), axis=1)
    
    # Check if the sum of each row equals n
    row_sum_equals_n = np.sum(X, axis=1) == n
    
    # Select rows that meet both conditions
    selected_rows = X[np.logical_and(is_integer, row_sum_equals_n)]
    
    return selected_rows

# Example 2D array X and integer n
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [1, 2, 3]])

n = 6

# Select rows from X that meet the criteria
selected_rows = select_multinomial_rows(X, n)

print("Selected rows:")
print(selected_rows)


Selected rows:
[[1 2 3]
 [1 2 3]]


# 100.

In [112]:
def bootstrap_confidence_interval(X, num_samples, alpha=0.05):
    # Initialize array to store means of bootstrap samples
    bootstrap_means = np.zeros(num_samples)
    
    # Resample the elements of X with replacement and compute the mean of each sample
    for i in range(num_samples):
        sample = np.random.choice(X, size=len(X), replace=True)
        bootstrap_means[i] = np.mean(sample)
    
    # Compute confidence intervals using percentiles
    lower_percentile = 100 * (alpha / 2)
    upper_percentile = 100 * (1 - alpha / 2)
    confidence_interval = np.percentile(bootstrap_means, [lower_percentile, upper_percentile])
    
    return confidence_interval

# Example 1D array X
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Number of bootstrap samples
num_samples = 1000

# Compute bootstrap confidence intervals
confidence_interval = bootstrap_confidence_interval(X, num_samples)

print("Bootstrap confidence interval for the mean (95%):", confidence_interval)


Bootstrap confidence interval for the mean (95%): [3.8 7.3]
